### ISSUE TITLE
在修改角色名后，PROFILEMAP未及时更新，导致无法使用新的角色名登录

### ISSUE THREAD

**Issue by RicePasteM** [yige233/nodeYggdrasil#1]
可能的解决方案：
// profile.ts
async setName(newName: string): Promise<Profile> {
    Profile.nameCheck(newName);
    this.name = newName;
    await this.save();
    PROFILEMAP.set([this.name, this.id], this); // 新增的代码
    return this;
}

**Comment by yige233** [comment]
我看了下，确实有你说的`无法使用新的角色名登录`的问题，但并非由于PROFILEMAP未及时更新，而是由于更新PROFILEMAP的时候，没有在作为key的数组中添加新角色名的小写格式。`User.authenticate`方法是将输入的用户名转为小写后，再在USERMAP和PROFILEMAP中查找对应的数据。然而由于更新的PROFILEMAP中没有新角色名的小写格式，所以查找不到用户，因此拒绝登录。但如果新角色名中没有大写字母，那么就可以成功登录。

可以对比`profile.ts`的第71行和第233行，这两行分别负责创建和更新PROFILEMAP，应该是一样的，是我疏漏了

新的代码对PROFILEMAP的根源下手，修改了`Utils.arrMap()`方法，这样就不需要到处调用`.toLowerCase()`方法了，避免这种遗漏了小写的sb问题再次出现
