### ISSUE TITLE
使用frp(开启了Proxy Protocol)并套了CloudFlare的问题

### ISSUE THREAD

**Issue by TomatoGarden666** [yige233/nodeYggdrasil#2]
使用frp(开启了Proxy Protocol)并套了CloudFlare,现在proxyCount数值应该为多少？
填1返回了错误的用户IP(162.158.90.231,cloudflare的IP)
填2返回了249.192.29.239，一个保留地址

**Comment by yige233** [comment]
先去掉CloudFlare，proxyCount填1，看看能不能获得到正确的IP

**Comment by TomatoGarden666** [comment]
好的，我先测试一下，待会给您回复！

**Comment by TomatoGarden666** [comment]
那么请问trustXRealIP是否需要设置为true呢？

**Comment by yige233** [comment]
> 那么请问trustXRealIP是否需要设置为true呢？

一般不用，除非你的代理服务器有特意设置X-Real-IP的请求头

**Comment by TomatoGarden666** [comment]
好的，我尝试后成功获取了客户端IP，但是如果我要套cloudflare该怎么办呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月19日(周一) 晚上8:09
收件人: ***@***.***&gt;;
抄送: "Guancheng ***@***.******@***.***&gt;;
主题: Re: [yige233/nodeYggdrasil] 使用frp(开启了Proxy Protocol)并套了CloudFlare的问题 (Issue #2)




  
那么请问trustXRealIP是否需要设置为true呢？
  
一般不用，除非你的代理服务器有特意设置X-Real-IP的请求头

**Comment by TomatoGarden666** [comment]
或者 我也可以不用CloudFlare，直接进行访问，但是我需要一个https的配置，请问如何
配置？

**Comment by TomatoGarden666** [comment]
我给您我的皮肤站网址吧！另外还有网页的FAVICON.ICO这些的配置怎么弄？
我的皮肤站网址:skin.hwantai.top

**Comment by yige233** [comment]
> 好的，我尝试后成功获取了客户端IP，但是如果我要套cloudflare该怎么办呢？

这么说应该是cf那边的配置有问题了，不过理论上只要cf设置好dns解析然后点亮代理状态的小云朵就好了，然后proxyCount +1

> 或者 我也可以不用CloudFlare，直接进行访问，但是我需要一个https的配置，请问如何 配置？

这个你可以再给frp反代后的地址再套一层caddy、nginx或者apache，并在这些软件上设置tls

> 另外还有网页的FAVICON.ICO这些的配置怎么弄？

制作一个你喜欢的favicon.ico，放到public目录下就可以了

**Comment by yige233** [comment]
> 我尝试了使用nginx进行反向代理，可是这并不能获取用户的真实IP，请问我应该把哪些nodeYggdrasil的配置修改？

我不知道你具体的代理的层次是什么样的，所以不太好下判断

你可以这样：frp通过tcp类型反代nodeYggdrasil，然后nginx反代frp，nodeYggdrasil把trustXRealIP设为true，并确保所有访问都经过nginx。

nginx会给所有请求设置正确的x-real-ip请求头，frp不对请求做任何修改，nodeYggdrasil则是信任x-real-ip，这样就可以获取到访问者的真实ip

**Comment by TomatoGarden666** [comment]
在刚才我已经尝试过，nginx启用proxy protocol会导致无法访问，所以我将在cloudflare中启用相关设置！十分感谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 下午2:02
收件人: ***@***.***&gt;;
抄送: "Guancheng ***@***.******@***.***&gt;;
主题: Re: [yige233/nodeYggdrasil] 使用frp(开启了Proxy Protocol)并套了CloudFlare的问题 (Issue #2)




  
我尝试了使用nginx进行反向代理，可是这并不能获取用户的真实IP，请问我应该把哪些nodeYggdrasil的配置修改？
  
我不知道你具体的代理的层次是什么样的，所以不太好下判断
 
你可以这样：frp通过tcp类型反代nodeYggdrasil，然后nginx反代frp，nodeYggdrasil把trustXRealIP设为true，并确保所有访问都经过nginx。
 
nginx会给所有请求设置正确的x-real-ip请求头，frp不对请求做任何修改，nodeYggdrasil则是信任x-real-ip，这样就可以获取到访问者的真实ip
