### ISSUE TITLE
disableUserInviteCode设置为true之后仍然需要邀请码才能注册

### ISSUE THREAD

**Issue by TomatoGarden666** [yige233/nodeYggdrasil#3]
已经在配置文件中将disableUserInviteCode设置为true，但是仍然需要邀请码才能注册

**Comment by yige233** [comment]
disableUserInviteCode指的是：禁止使用任何**用户**的邀请码进行新用户注册。也就是说注册仍然需要邀请码，但是不能使用用户邀请码。

如果你需要达到“任何人都可以注册”的效果，只需要设置并公开一个系统邀请码，注册时使用该邀请码注册即可。

**Comment by TomatoGarden666** [comment]
好的，谢谢！
