### ISSUE TITLE
页面打开后白屏

### ISSUE THREAD

**Issue by ggc32** [yige233/nodeYggdrasil#4]
页面打开后白屏，打开F12控制台后提示`Uncaught SyntaxError: Unexpected identifier 'assert' (at main.js:1:38)`
浏览器：Microsoft Edge 版本 126.0.2592.68 (正式版本) (64 位)
手机浏览器可以正常打开

**Comment by yige233** [comment]
前端页面用了`assert`语法来导入css文件，然而`assert`很快就被`with`替代了，Edge 126已经不支持`assert`了

但如果换成`with`的话，Edge应该是可以打开了，但手机浏览器版本很可能不够新，反而打不开……

等我看看有没有什么两全其美的可以接着用新语法的办法

**Comment by yige233** [comment]
在[c85b6d2](https://github.com/yige233/nodeYggdrasil/commit/c85b6d2d8988c2537bc8372c933ce38a34ca5a2f)修好了
